# Generated by Django 2.1.3 on 2019-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_latestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='latestMessage',
            field=models.TextField(),
        ),
    ]
