# Generated by Django 2.1.3 on 2019-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
