# Generated by Django 2.1.5 on 2019-03-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_requests_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
