# Generated by Django 2.1.5 on 2019-04-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190404_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default_request.jpg', upload_to='requests_user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Requests')),
            ],
        ),
    ]
