# Generated by Django 2.1.3 on 2019-02-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_requests_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='seen',
        ),
        migrations.AddField(
            model_name='seenrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Requests'),
        ),
        migrations.AddField(
            model_name='seenrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
