# Generated by Django 2.1.5 on 2019-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190314_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobhire',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
