# Generated by Django 2.1.5 on 2019-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190517_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('GBP', '£'), ('AUD', '$'), ('USD', '$'), ('CAD', '$'), ('HRK', 'kn'), ('CZK', 'Kč'), ('HUF', 'Ft'), ('CHF', 'Fr'), ('RON', 'lei'), ('RSD', 'din'), ('SEK', 'kr')], default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='requests',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('GBP', '£'), ('AUD', '$'), ('USD', '$'), ('CAD', '$'), ('HRK', 'kn'), ('CZK', 'Kč'), ('HUF', 'Ft'), ('CHF', 'Fr'), ('RON', 'lei'), ('RSD', 'din'), ('SEK', 'kr')], default='EUR', max_length=10),
        ),
    ]
