# Generated by Django 2.1.5 on 2019-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190522_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD (Australian dollar)'), ('USD', 'USD (United States dollar)'), ('CAD', 'CAD (Canadian dollar)'), ('HRK', 'HRK'), ('CZK', 'CZK'), ('HUF', 'HUF'), ('CHF', 'CHF'), ('RON', 'RON'), ('RSD', 'RSD'), ('SEK', 'SEK')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD (Australian dollar)'), ('USD', 'USD (United States dollar)'), ('CAD', 'CAD (Canadian dollar)'), ('HRK', 'HRK'), ('CZK', 'CZK'), ('HUF', 'HUF'), ('CHF', 'CHF'), ('RON', 'RON'), ('RSD', 'RSD'), ('SEK', 'SEK')], default='EUR', max_length=10),
        ),
    ]
