# Generated by Django 2.1.3 on 2019-02-28 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_appliccation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('date_hired', models.DateTimeField(auto_now_add=True)),
                ('repairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobhire',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Requests'),
        ),
    ]
