# Generated by Django 2.1.5 on 2019-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190316_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_hires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
