# Generated by Django 2.1.5 on 2019-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190316_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='url_to_go',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
