# Generated by Django 2.1.5 on 2019-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rate_url_to_go'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='url_to_go',
        ),
        migrations.AddField(
            model_name='clientnotifications',
            name='url_to_go',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='repairmannotifications',
            name='url_to_go',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
